/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.components.iValue.impl;

import ui.components.iValue.IValue;
import vrednosniValidator.VrednosniValidator;
import vrednosniValidator.impl.VrednosniValidatorDefault;

/**
 *
 * @author Aleksa
 */
public class InputPanelPassword extends javax.swing.JPanel implements IValue{

        private vrednosniValidator.VrednosniValidator validator;
    
    /**
     * Creates new form InputPanelPassword
     */
    public InputPanelPassword() {
        initComponents();
        validator = new VrednosniValidatorDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabText = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jlabError = new javax.swing.JLabel();

        jlabText.setText("jLabel1");

        jpassword.setText("jPasswordField1");

        jlabError.setForeground(new java.awt.Color(255, 0, 0));
        jlabError.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlabError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabText, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabText)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabError))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabError;
    private javax.swing.JLabel jlabText;
    private javax.swing.JPasswordField jpassword;
    // End of variables declaration//GEN-END:variables

    
    //refactor:
    @Override
    public Object getValue() throws Exception {
        validator.validate();
        return new String(jpassword.getPassword());
    }

    @Override
    public void setValue(Object value) {
        jpassword.setText((String) value);
    }

    @Override
    public void inicialize(Object initValue) {
        jpassword.setText((String) initValue);
    }

    public javax.swing.JLabel getJlabError() {
        return jlabError;
    }

    public javax.swing.JLabel getJlabText() {
        return jlabText;
    }

    public javax.swing.JPasswordField getJpassword() {
        return jpassword;
    }

    @Override
    public void setValidator(VrednosniValidator validator) {
        this.validator = validator;
    }
    
    
}
